### PR TITLE
Adding typescript declarations.

### PR DESCRIPTION
**Pull request by majo44**
Fixing #19

This PR have a 2 goals:

1. Move types declarations directly to library 
2. Create very strict types declarations which will plays well together typescript static types (eg. `StringType` can be used only to validate properties which are marked as `string`)

### CODE REVIEW

**Comment by majo44** [comment]
Work in progress, I still work on tests.

**Comment by simonguo** [comment]
This is great, thank you

**Comment by simonguo** [comment]
@majo44 Is there anything else that needs to be updated? If not I will want to merge it.

**Comment by majo44** [comment]
I wanted to make more tests in my side project, but last time I did not had more time for that. So far definitions plays well, so if you want we can merge.

**Pull request merged**
